#!/bin/bash

clean_git_branch() {
  git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d
}

capy() {
  conda activate $1
}

cdpy() {
  conda deactivate
}

jpnb() {
  jupyter notebook
}
